name: Update go.sum

on:
  workflow_dispatch:  # Permite ejecutar el flujo de trabajo manualmente

jobs:
  update-go-sum:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Download dependencies
        run: go mod download

      - name: Update go.sum
        run: go mod tidy

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'go.sum'
          message: 'Update go.sum'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
